In [26]:
import pandas as pd
import numpy as np

import time
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import confusion_matrix, recall_score, roc_auc_score

In [3]:
data = pd.read_csv('data_linear.csv')
data.shape

(1348099, 78)

In [4]:
pd.set_option('display.max_columns', None)
data.head()

Unnamed: 0  int_rate  annual_inc  loan_status    dti  delinq_2yrs  \
0           0     13.99     55000.0            1   5.91          0.0   
1           1     11.99     65000.0            1  16.06          1.0   
2           2     10.78     63000.0            1  10.78          0.0   
3           3     22.45    104433.0            1  25.37          1.0   
4           4     13.44     34000.0            1  10.20          0.0   

   inq_last_6mths  mths_since_last_delinq  pub_rec  revol_bal  revol_util  \
0             1.0                    30.0      0.0     2765.0        29.7   
1             4.0                     6.0      0.0    21470.0        19.2   
2             0.0                    31.0      0.0     7869.0        56.2   
3             3.0                    12.0      0.0    21929.0        64.5   
4             0.0                    31.0      0.0     8822.0        68.4   

   last_pymnt_amnt  last_fico_range_high  last_fico_range_low  \
0           122.67                 564.0                560.0   
1           926.35                 699.0                695.0   
2         15813.30                 704.0                700.0   
3         10128.96                 704.0                700.0   
4          7653.56                 759.0                755.0   

   collections_12_mths_ex_med  mths_since_last_major_derog  acc_now_delinq  \
0                         0.0                         30.0             0.0   
1                         0.0                         44.0             0.0   
2                         0.0                         44.0             0.0   
3                         0.0                         44.0             0.0   
4                         0.0                         44.0             0.0   

   tot_coll_amt  open_acc_6m  open_act_il  open_il_12m  open_il_24m  \
0         722.0          2.0          2.0          0.0          1.0   
1           0.0          1.0          1.0          0.0          1.0   
2           0.0          0.0          1.0          0.0          4.0   
3           0.0          1.0          3.0          0.0          3.0   
4           0.0          0.0          1.0          0.0          0.0   

   mths_since_rcnt_il  total_bal_il  il_util  open_rv_12m  open_rv_24m  \
0                21.0        4981.0     36.0          3.0          3.0   
1                19.0       18005.0     73.0          2.0          3.0   
2                19.0       10827.0     73.0          0.0          2.0   
3                14.0       73839.0     84.0          4.0          7.0   
4               338.0        3976.0     99.0          0.0          0.0   

   max_bal_bc  all_util  total_rev_hi_lim  inq_fi  total_cu_tl  inq_last_12m  \
0       722.0      34.0            9300.0     3.0          1.0           4.0   
1      6472.0      29.0          111800.0     0.0          0.0           6.0   
2      2081.0      65.0           14000.0     2.0          5.0           1.0   
3      9702.0      78.0           34000.0     2.0          1.0           3.0   
4      4522.0      76.0           12900.0     0.0          0.0           0.0   

   acc_open_past_24mths  avg_cur_bal  bc_open_to_buy  bc_util  \
0                   4.0      20701.0          1506.0     37.2   
1                   4.0       9733.0         57830.0     27.1   
2                   6.0      31617.0          2737.0     55.9   
3                  10.0      27644.0          4567.0     77.5   
4                   0.0       2560.0           844.0     91.0   

   chargeoff_within_12_mths  delinq_amnt  mo_sin_old_il_acct  \
0                       0.0          0.0               148.0   
1                       0.0          0.0               113.0   
2                       0.0          0.0               125.0   
3                       0.0          0.0               128.0   
4                       0.0          0.0               338.0   

   mo_sin_old_rev_tl_op  mo_sin_rcnt_rev_tl_op  mo_sin_rcnt_tl  mort_acc  \
0                 128.0                   

In [5]:
data = data.drop(['Unnamed: 0'], axis = 1)
data.describe()

int_rate    annual_inc   loan_status           dti   delinq_2yrs  \
count  1.348099e+06  1.348099e+06  1.348099e+06  1.348099e+06  1.348099e+06   
mean   1.324156e+01  7.623771e+04  8.001927e-01  1.827413e+01  3.176258e-01   
std    4.765685e+00  6.992264e+04  3.998555e-01  1.115395e+01  8.777361e-01   
min    5.310000e+00  0.000000e+00  0.000000e+00 -1.000000e+00  0.000000e+00   
25%    9.750000e+00  4.575000e+04  1.000000e+00  1.179000e+01  0.000000e+00   
50%    1.274000e+01  6.500000e+04  1.000000e+00  1.761000e+01  0.000000e+00   
75%    1.599000e+01  9.000000e+04  1.000000e+00  2.405000e+01  0.000000e+00   
max    3.099000e+01  1.099920e+07  1.000000e+00  9.990000e+02  3.900000e+01   

       inq_last_6mths  mths_since_last_delinq       pub_rec     revol_bal  \
count    1.348099e+06            1.348099e+06  1.348099e+06  1.348099e+06   
mean     6.621895e-01            3.263311e+01  2.150450e-01  1.627072e+04   
std      9.600654e-01            1.552495e+01  6.014662e-01  2.247751e+04   
min      0.000000e+00            0.000000e+00  0.000000e+00  0.000000e+00   
25%      0.000000e+00            3.100000e+01  0.000000e+00  5.936000e+03   
50%      0.000000e+00            3.100000e+01  0.000000e+00  1.113000e+04   
75%      1.000000e+00            3.100000e+01  0.000000e+00  1.975800e+04   
max      3.300000e+01            2.260000e+02  8.600000e+01  2.904836e+06   

         revol_util  last_pymnt_amnt  last_fico_range_high  \
count  1.348099e+06     1.348099e+06          1.348099e+06   
mean   5.181100e+01     5.415757e+03          6.772483e+02   
std    2.452166e+01     7.114250e+03          8.139900e+01   
min    0.000000e+00     0.000000e+00          0.000000e+00   
25%    3.350000e+01     3.975600e+02          6.290000e+02   
50%    5.220000e+01     2.031330e+03          6.940000e+02   
75%    7.070000e+01     8.235875e+03          7.340000e+02   
max    8.923000e+02     4.219205e+04          8.500000e+02   

       last_fico_range_low  collections_12_mths_ex_med  \
count         1.348099e+06                1.348099e+06   
mean          6.601138e+02                1.709889e-02   
std           1.328032e+02                1.467672e-01   
min           0.000000e+00                0.000000e+00   
25%           6.250000e+02                0.000000e+00   
50%           6.900000e+02                0.000000e+00   
75%           7.300000e+02                0.000000e+00   
max           8.450000e+02                2.000000e+01   

       mths_since_last_major_derog  acc_now_delinq  tot_coll_amt  \
count                 1.348099e+06    1.348099e+06  1.348099e+06   
mean                  4.392159e+01    5.038206e-03  2.363829e+02   
std                   1.095217e+01    7.710064e-02  1.077268e+04   
min                   0.000000e+00    0.000000e+00  0.000000e+00   
25%                   4.400000e+01    0.000000e+00  0.000000e+00   
50%                   4.400000e+01    0.000000e+00  0.000000e+00   
75%                   4.400000e+01    0.000000e+00  0.000000e+00   
max                   2.260000e+02    1.400000e+01  9.152545e+06   

        open_acc_6m   open_act_il   open_il_12m   open_il_24m  \
count  1.348099e+06  1.348099e+06  1.348099e+06  1.348099e+06   
mean   1.020160e+00  2.316073e+00  3.096241e-01  1.296217e+00   
std    7.637857e-01  1.927626e+00  7.334307e-01  1.124970e+00   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    1.000000e+00  2.000000e+00  0.000000e+00  1.000000e+00   
50%    1.000000e+00  2.000000e+00  0.000000e+00  1.000000e+00   
75%    1.000000e+00  2.000000e+00  0.000000e+00  1.000000e+00   
max    1.800000e+01  5.700000e+01  2.500000e+01  5.100000e+01   

       mths_since_rcnt_il  total_bal_il       il_util   open_rv_12m  \
count        1.348099e+06  1.348099e+06  1.348099e+06  1.348099e+06   
mean         1.555974e+01  2.820576e+04  7.180065e+01  1.167850e+00   
std          1.582712e+01  2.780428e+04  1.345839e+01  1.015670e+00   
min          0.000000e+00  0.000000e+00 

In [6]:
Target = data['loan_status']
Features = data.drop(['loan_status'], axis = 1)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(Features, Target, test_size = 0.3, random_state = 42)

In [8]:
KF = KFold(3, shuffle = True, random_state = 42)

In [9]:
X1 = StandardScaler().fit_transform(X_train)
X2 = StandardScaler().fit_transform(X_test)

# Logistic Regression

In [10]:
start1 = time.time()
Logit = SGDClassifier(loss='log', shuffle= True, n_jobs = -1, 
                      warm_start = True, class_weight = "balanced").fit(X1, y_train)
end1 = time.time()
Time1 = end1 - start1
print(Time1)

7.19819188117981


In [29]:
train_scores1 = cross_val_score(Logit, X1, y_train, cv = KF)
test_scores1 = cross_val_score(Logit, X2, y_test, cv = KF)

train_ac1 = round(Logit.score(X1, y_train), 4)
test_ac1 = round(Logit.score(X2, y_test), 4)
recall1 = round(recall_score(y_test, Logit.predict(X2)), 4)
roc1 = round(roc_auc_score(y_test, Logit.predict_proba(X2)[:, 1]), 4)

print(train_scores1)
print(test_scores1)
print(train_ac1)
print(test_ac1)
print(recall1)
print(roc1)

[0.92938005 0.92985351 0.93156386]
[0.92990134 0.93068022 0.92947111]
0.931
0.9315
0.9287
0.9822


# SVM

In [15]:
from sklearn.kernel_approximation import Nystroem

X1_svm = Nystroem(random_state = 42, n_jobs = -1, n_components = 77, gamma = 1/77).fit_transform(X1)
X2_svm = Nystroem(random_state = 42, n_jobs = -1, n_components = 77, gamma = 1/77).fit_transform(X2)

In [34]:
from sklearn.calibration import CalibratedClassifierCV

start2 = time.time()
SVM = SGDClassifier(loss='hinge', shuffle= True, n_jobs = -1, random_state = 42, warm_start = True)
calibrated_svm = CalibratedClassifierCV(SVM, method='sigmoid').fit(X1_svm, y_train)
end2 = time.time()
Time2 = end2 - start2
print(Time2)

17.45238161087036


In [36]:
train_scores2 = cross_val_score(calibrated_svm, X1_svm, y_train, cv = KF)
test_scores2= cross_val_score(calibrated_svm, X2_svm, y_test, cv = KF)

train_ac2 = round(calibrated_svm.score(X1_svm, y_train), 4)
test_ac2 = round(calibrated_svm.score(X2_svm, y_test), 4)
recall2 = round(recall_score(y_test, calibrated_svm.predict(X2_svm)), 4)
roc2 = round(roc_auc_score(y_test, calibrated_svm.predict_proba(X2_svm)[:, 1]), 4)

print(train_scores2)
print(test_scores2)
print(train_ac2)
print(test_ac2)
print(recall2)
print(roc2)

[0.91417772 0.91420923 0.91423467]
[0.91216527 0.91265485 0.91190564]
0.9144
0.734
0.8888
0.5546


# Naive Bayes

In [18]:
start3 = time.time()
GNB = GaussianNB().fit(X1, y_train)
end3 = time.time()
Time3 = end3 - start3
print(Time3)

2.1127045154571533


In [32]:
train_scores3 = cross_val_score(GNB, X1, y_train, cv = KF)
test_scores3 = cross_val_score(GNB, X2, y_test, cv = KF)

train_ac3 = round(GNB.score(X1, y_train), 4)
test_ac3 = round(GNB.score(X2, y_test), 4)
recall3 = round(recall_score(y_test, GNB.predict(X2)), 4)
roc3 = round(roc_auc_score(y_test, GNB.predict_proba(X2)[:, 1]), 4)

print(train_scores3)
print(test_scores3)
print(train_ac3)
print(test_ac3)
print(recall3)
print(roc3)

[0.89851124 0.90899872 0.90724386]
[0.87685632 0.8760181  0.86802166]
0.9073
0.9069
0.961
0.9539


Save result as csv

In [40]:
df = pd.DataFrame([['Logit', train_ac1, test_ac1, recall1, roc1],
                   ['SVM', train_ac2, test_ac2, recall2, roc2],
                   ['Naive Bayes', train_ac3, test_ac3, recall3, roc3]], 
                    columns=['model', 'train score','test score','recall score', 'ROC AUC score'])
df

model  train score  test score  recall score  ROC AUC score
0        Logit       0.9310      0.9315        0.9287         0.9822
1          SVM       0.9144      0.7340        0.8888         0.5546
2  Naive Bayes       0.9073      0.9069        0.9610         0.9539

In [41]:
df.to_csv('result.csv')