In [1]:
import pandas as pd
import numpy as np

import time
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import confusion_matrix, recall_score, roc_auc_score
from imblearn.under_sampling import RandomUnderSampler

In [2]:
data = pd.read_csv('data_non_linear.csv')
data.shape

(1348099, 105)

In [8]:
data['loan_status'].value_counts()

1    1078739
0     269360
Name: loan_status, dtype: int64

In [5]:
pd.set_option('display.max_columns', None)
data.head()

Unnamed: 0  loan_amnt  int_rate  installment  annual_inc  loan_status  \
0           0     3600.0     13.99       123.03     55000.0            1   
1           1    24700.0     11.99       820.28     65000.0            1   
2           2    20000.0     10.78       432.66     63000.0            1   
3           3    10400.0     22.45       289.91    104433.0            1   
4           4    11950.0     13.44       405.18     34000.0            1   

     dti  delinq_2yrs  fico_range_low  fico_range_high  inq_last_6mths  \
0   5.91          0.0           675.0            679.0             1.0   
1  16.06          1.0           715.0            719.0             4.0   
2  10.78          0.0           695.0            699.0             0.0   
3  25.37          1.0           695.0            699.0             3.0   
4  10.20          0.0           690.0            694.0             0.0   

   mths_since_last_delinq  open_acc  pub_rec  revol_bal  revol_util  \
0                    30.0       7.0      0.0     2765.0        29.7   
1                     6.0      22.0      0.0    21470.0        19.2   
2                    31.0       6.0      0.0     7869.0        56.2   
3                    12.0      12.0      0.0    21929.0        64.5   
4                    31.0       5.0      0.0     8822.0        68.4   

   total_acc  out_prncp  out_prncp_inv   total_pymnt  total_pymnt_inv  \
0       13.0        0.0            0.0   4421.723917          4421.72   
1       38.0        0.0            0.0  25679.660000         25679.66   
2       18.0        0.0            0.0  22705.924294         22705.92   
3       35.0        0.0            0.0  11740.500000         11740.50   
4        6.0        0.0            0.0  13708.948530         13708.95   

   total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  \
0           3600.0         821.72                 0.0         0.0   
1          24700.0         979.66                 0.0         0.0   
2          20000.0        2705.92                 0.0         0.0   
3          10400.0        1340.50                 0.0         0.0   
4          11950.0        1758.95                 0.0         0.0   

   collection_recovery_fee  last_pymnt_amnt  last_fico_range_high  \
0                      0.0           122.67                 564.0   
1                      0.0           926.35                 699.0   
2                      0.0         15813.30                 704.0   
3                      0.0         10128.96                 704.0   
4                      0.0          7653.56                 759.0   

   last_fico_range_low  collections_12_mths_ex_med  \
0                560.0                         0.0   
1                695.0                         0.0   
2                700.0                         0.0   
3                700.0                         0.0   
4                755.0                         0.0   

   mths_since_last_major_derog  policy_code  acc_now_delinq  tot_coll_amt  \
0                         30.0          1.0             0.0         722.0   
1                         44.0          1.0             0.0           0.0   
2                         44.0          1.0             0.0           0.0   
3                         44.0          1.0             0.0           0.0   
4                         44.0          1.0             0.0           0.0   

   tot_cur_bal  open_acc_6m  open_act_il  open_il_12m  open_il_24m  \
0     144904.0          2.0          2.0          0.0          1.0   
1     204396.0          1.0          1.0          0.0          1.0   
2     189699.0          0.0          1.0          0.0          4.0   
3     331730.0          1.0          3.0          0.0          3.0   
4      12798.0          0.0          1.0          0.0          0.0   

   mths_since_rcnt_il  total_bal_il  il_util  open_rv_12m  open_rv_24m  \
0                21.0        4981.0     36.0          3.0          3.0   
1                19.0       18005.0     73.0    

In [6]:
data = data.drop(['Unnamed: 0'], axis = 1)
data.describe()

loan_amnt      int_rate   installment    annual_inc   loan_status  \
count  1.348099e+06  1.348099e+06  1.348099e+06  1.348099e+06  1.348099e+06   
mean   1.440900e+04  1.324156e+01  4.377778e+02  7.623771e+04  8.001927e-01   
std    8.716138e+03  4.765685e+00  2.614972e+02  6.992264e+04  3.998555e-01   
min    5.000000e+02  5.310000e+00  4.930000e+00  0.000000e+00  0.000000e+00   
25%    7.975000e+03  9.750000e+00  2.482800e+02  4.575000e+04  1.000000e+00   
50%    1.200000e+04  1.274000e+01  3.750400e+02  6.500000e+04  1.000000e+00   
75%    2.000000e+04  1.599000e+01  5.802200e+02  9.000000e+04  1.000000e+00   
max    4.000000e+04  3.099000e+01  1.719830e+03  1.099920e+07  1.000000e+00   

                dti   delinq_2yrs  fico_range_low  fico_range_high  \
count  1.348099e+06  1.348099e+06    1.348099e+06     1.348099e+06   
mean   1.827413e+01  3.176258e-01    6.961622e+02     7.001624e+02   
std    1.115395e+01  8.777361e-01    3.185079e+01     3.185143e+01   
min   -1.000000e+00  0.000000e+00    6.100000e+02     6.140000e+02   
25%    1.179000e+01  0.000000e+00    6.700000e+02     6.740000e+02   
50%    1.761000e+01  0.000000e+00    6.900000e+02     6.940000e+02   
75%    2.405000e+01  0.000000e+00    7.100000e+02     7.140000e+02   
max    9.990000e+02  3.900000e+01    8.450000e+02     8.500000e+02   

       inq_last_6mths  mths_since_last_delinq      open_acc       pub_rec  \
count    1.348099e+06            1.348099e+06  1.348099e+06  1.348099e+06   
mean     6.621895e-01            3.263311e+01  1.159043e+01  2.150450e-01   
std      9.600654e-01            1.552495e+01  5.474622e+00  6.014662e-01   
min      0.000000e+00            0.000000e+00  0.000000e+00  0.000000e+00   
25%      0.000000e+00            3.100000e+01  8.000000e+00  0.000000e+00   
50%      0.000000e+00            3.100000e+01  1.100000e+01  0.000000e+00   
75%      1.000000e+00            3.100000e+01  1.400000e+01  0.000000e+00   
max      3.300000e+01            2.260000e+02  9.000000e+01  8.600000e+01   

          revol_bal    revol_util     total_acc     out_prncp  out_prncp_inv  \
count  1.348099e+06  1.348099e+06  1.348099e+06  1.348099e+06   1.348099e+06   
mean   1.627072e+04  5.181100e+01  2.497592e+01  2.840541e-01   2.840541e-01   
std    2.247751e+04  2.452166e+01  1.200344e+01  6.832063e+01   6.832063e+01   
min    0.000000e+00  0.000000e+00  1.000000e+00  0.000000e+00   0.000000e+00   
25%    5.936000e+03  3.350000e+01  1.600000e+01  0.000000e+00   0.000000e+00   
50%    1.113000e+04  5.220000e+01  2.300000e+01  0.000000e+00   0.000000e+00   
75%    1.975800e+04  7.070000e+01  3.200000e+01  0.000000e+00   0.000000e+00   
max    2.904836e+06  8.923000e+02  1.760000e+02  2.822201e+04   2.822201e+04   

        total_pymnt  total_pymnt_inv  total_rec_prncp  total_rec_int  \
count  1.348099e+06     1.348099e+06     1.348099e+06   1.348099e+06   
mean   1.481171e+04     1.478309e+04     1.217126e+04   2.397581e+03   
std    1.034951e+04     1.035074e+04     8.865794e+03   2.599631e+03   
min    0.000000e+00     0.000000e+00     0.000000e+00   0.000000e+00   
25%    6.826669e+03     6.800135e+03     5.000000e+03   7.665400e+02   
50%    1.211771e+04     1.209122e+04     1.000000e+04   1.568850e+03   
75%    2.057062e+04     2.053642e+04     1.720000e+04   3.029890e+03   
max    6.329688e+04     6.329688e+04     4.000000e+04   2.819250e+04   

       total_rec_late_fee    recoveries  collection_recovery_fee  \
count        1.348099e+06  1.348099e+06             1.348099e+06   
mean         1.587746e+00  2.412753e+02             4.021709e+01   
std          1.077187e+01  9.566408e+02             1.680003e+02   
min         -5.100000e-09  0.000000e+00             0.000000e+00   
25%          0.000000e+00  0.000000e+00             0.000000e+00   
50%          0.000000e+00  0.000000e+00             0.000000e+00   
75%          0.000000e+00  0.000000e+00             0.000000e+00   
max          1.188830e+03  3.985955e+04             7.17471

In [7]:
Target = data['loan_status']
Features = data.drop(['loan_status'], axis = 1)

In [40]:
# Under sampling the imbalanced dataset
undersample = RandomUnderSampler(sampling_strategy = 0.5, random_state = 42)
features_balanced, target_balanced = undersample.fit_resample(Features, Target)
print(features_balanced.shape)
print(target_balanced.shape)

(808080, 103)
(808080,)


In [41]:
X_train, X_test, y_train, y_test = train_test_split(features_balanced, target_balanced, test_size = 0.3, random_state = 42)

In [28]:
KF = KFold(3, shuffle = True, random_state= 42)

# Random Forest

In [42]:
start1 = time.time()
forest = RandomForestClassifier(n_jobs = -1, oob_score = True, 
                                random_state = 42, class_weight= "balanced").fit(X_train, y_train)
end1 = time.time()
Time1 = end1 - start1
print(Time1)

254.60912919044495


In [43]:
train_scores1 = cross_val_score(forest, X_train, y_train, cv = KF)
test_scores1 = cross_val_score(forest, X_test, y_test, cv = KF)

train_ac1 = round(forest.score(X_train, y_train), 4)
test_ac1 = round(forest.score(X_test, y_test), 4)
recall1 = round(recall_score(y_test, forest.predict(X_test)), 4)
roc1 = round(roc_auc_score(y_test, forest.predict_proba(X_test)[:, 1]), 4)

print(train_scores1)
print(test_scores1)
print(train_ac1)
print(test_ac1)
print(recall1)
print(roc1)

[0.99641478 0.99672239 0.99621325]
[0.99560687 0.99507475 0.99591625]
1.0
0.9969
0.9997
0.9998


In [56]:
forest.score(X_train, y_train)

0.9999964642821786

In [46]:
confusion_matrix(y_test, forest.predict(X_test))

array([[ 80047,    712],
       [    45, 161620]], dtype=int64)

# Gradient Boosting

In [48]:
start2 = time.time()
boosting = GradientBoostingClassifier(random_state = 42).fit(X_train, y_train)
end2 = time.time()
Time2 = end2 - start2
print(Time2)

1113.1691370010376


In [49]:
train_scores2 = cross_val_score(boosting, X_train, y_train, cv = KF)
test_scores2 = cross_val_score(boosting, X_test, y_test, cv = KF)

train_ac2 = round(boosting.score(X_train, y_train), 4)
test_ac2 = round(boosting.score(X_test, y_test), 4)
recall2 = round(recall_score(y_test, boosting.predict(X_test)), 4)
roc2 = round(roc_auc_score(y_test, boosting.predict_proba(X_test)[:, 1]), 4)

print(train_scores2)
print(test_scores2)
print(train_ac2)
print(test_ac2)
print(recall2)
print(roc2)

[0.99586851 0.99608596 0.99603292]
[0.99605237 0.995347   0.99629987]
0.9962
0.9962
0.9998
0.9997


In [52]:
confusion_matrix(y_test, forest.predict(X_test))

array([[ 80047,    712],
       [    45, 161620]], dtype=int64)

In [61]:
df = pd.DataFrame([['Random Forest', train_ac1, test_ac1, recall1, roc1],
                  ['Gradient Boosting', train_ac2, test_ac2, recall2, roc2]], 
                 columns=['model', 'train score','test score','recall score', 'ROC AUC score'])
df

model  train score  test score  recall score  ROC AUC score
0      Random Forest       1.0000      0.9969        0.9997         0.9998
1  Gradient Boosting       0.9962      0.9962        0.9998         0.9997

In [62]:
df2 = pd.read_csv('result.csv')

In [65]:
result = pd.concat([df, df2], ignore_index=True)
result.drop(['Unnamed: 0'], axis = 1, inplace = True)
result

model  train score  test score  recall score  ROC AUC score
0      Random Forest       1.0000      0.9969        0.9997         0.9998
1  Gradient Boosting       0.9962      0.9962        0.9998         0.9997
2              Logit       0.9310      0.9315        0.9287         0.9822
3                SVM       0.9144      0.7340        0.8888         0.5546
4        Naive Bayes       0.9073      0.9069        0.9610         0.9539